#!/usr/bin/env python3
"""Generate shell completion scripts from the registered VaultSync CLI help."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import subprocess
from typing import Sequence

from generate_cli_reference import COMMANDS, command_children, normalize_help, verify_inventory

OPTION = re.compile(r"(?<![\w-])--[a-z][a-z0-9-]*|(?<![\w-])-[a-z](?![\w-])")


def command_options(help_text: str) -> tuple[str, ...]:
    in_options = False
    options: list[str] = []
    for line in normalize_help(help_text).splitlines():
        if line == "OPTIONS:":
            in_options = True
            continue
        if in_options and line and not line.startswith(" "):
            break
        if in_options and line.lstrip().startswith("-"):
            signature = re.split(r"\s{2,}", line.strip(), maxsplit=1)[0]
            options.extend(OPTION.findall(signature))
    return tuple(dict.fromkeys(options))


def command_data(assembly: Path) -> tuple[dict[str, str], dict[str, str]]:
    if not assembly.is_file():
        raise FileNotFoundError(f"CLI assembly not found: {assembly}")
    help_cache: dict[tuple[str, ...], str] = {}

    def help_for(command: Sequence[str]) -> str:
        route = tuple(command)
        if route not in help_cache:
            completed = subprocess.run(
                ["dotnet", str(assembly), *route, "--help"], check=True,
                text=True, capture_output=True,
            )
            help_cache[route] = completed.stdout
        return help_cache[route]

    verify_inventory(help_for)
    children = {" ".join(route): " ".join(command_children(help_for(route))) for route in COMMANDS}
    children["completion"] = "bash zsh powershell"
    options = {" ".join(route): " ".join(command_options(help_for(route))) for route in COMMANDS}
    options[""] += " --version"
    return children, options


def bash_map(name: str, data: dict[str, str]) -> str:
    rows = [f"    '{route}') printf '%s' '{value}' ;;" for route, value in data.items() if value]
    return f"{name}() {{\n  case \"$1\" in\n" + "\n".join(rows) + "\n  esac\n}\n"


def render_bash(children: dict[str, str], options: dict[str, str]) -> str:
    return """# Generated by scripts/generate_cli_completions.py. Do not edit manually.
""" + bash_map("_vaultsync_children", children) + bash_map("_vaultsync_options", options) + """
_vaultsync_complete() {
  local current="${COMP_WORDS[COMP_CWORD]}" route='' word choices child
  local index
  for ((index = 1; index < COMP_CWORD; index++)); do
    word="${COMP_WORDS[index]}"
    choices="$(_vaultsync_children "$route")"
    case " $choices " in
      *" $word "*) route="${route:+$route }$word" ;;
    esac
  done
  if [[ "$current" == -* ]]; then
    choices="$(_vaultsync_options "$route")"
  else
    choices="$(_vaultsync_children "$route")"
  fi
  COMPREPLY=( $(compgen -W "$choices" -- "$current") )
}
complete -F _vaultsync_complete vaultsync
"""


def zsh_map(name: str, data: dict[str, str]) -> str:
    rows = [f"    '{route}') reply='{value}' ;;" for route, value in data.items() if value]
    return f"{name}() {{\n  case \"$1\" in\n" + "\n".join(rows) + "\n  esac\n}\n"


def render_zsh(children: dict[str, str], options: dict[str, str]) -> str:
    return """#compdef vaultsync
# Generated by scripts/generate_cli_completions.py. Do not edit manually.
""" + zsh_map("_vaultsync_children", children) + zsh_map("_vaultsync_options", options) + """
_vaultsync() {
  local route='' word reply='' choices=''
  local index
  for ((index = 2; index < CURRENT; index++)); do
    word="${words[index]}"
    reply=''
    _vaultsync_children "$route"
    case " $reply " in
      *" $word "*) route="${route:+$route }$word" ;;
    esac
  done
  reply=''
  if [[ "$words[CURRENT]" == -* ]]; then
    _vaultsync_options "$route"
  else
    _vaultsync_children "$route"
  fi
  compadd -Q -- ${(s: :)reply}
}
_vaultsync "$@"
"""


def powershell_map(name: str, data: dict[str, str]) -> str:
    rows = [f"        '{route}' {{ return '{value}' }}" for route, value in data.items() if value]
    return f"function {name}([string]$route) {{\n    switch ($route) {{\n" + "\n".join(rows) + "\n    }\n    return ''\n}\n"


def render_powershell(children: dict[str, str], options: dict[str, str]) -> str:
    return """# Generated by scripts/generate_cli_completions.py. Do not edit manually.
""" + powershell_map("Get-VaultSyncChildren", children) + powershell_map("Get-VaultSyncOptions", options) + """
Register-ArgumentCompleter -Native -CommandName vaultsync -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $route = ''
    foreach ($element in @($commandAst.CommandElements | Select-Object -Skip 1)) {
        if ($element.Extent.EndOffset -ge $cursorPosition) { break }
        $word = $element.Extent.Text.Trim('"', "'")
        $children = @((Get-VaultSyncChildren $route) -split ' ')
        if ($children -contains $word) {
            if ($route) { $route = "$route $word" } else { $route = $word }
        }
    }
    if ($wordToComplete.StartsWith('-')) {
        $choices = Get-VaultSyncOptions $route
    } else {
        $choices = Get-VaultSyncChildren $route
    }
    foreach ($choice in @($choices -split ' ')) {
        if ($choice -and $choice.StartsWith($wordToComplete, [StringComparison]::OrdinalIgnoreCase)) {
            [System.Management.Automation.CompletionResult]::new($choice, $choice, 'ParameterValue', $choice)
        }
    }
}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--assembly", default="src/VaultSync.CLI/bin/Debug/net10.0/VaultSync.CLI.dll")
    parser.add_argument("--output-dir", default="completions")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    children, options = command_data(Path(args.assembly).resolve())
    output = Path(args.output_dir).resolve()
    scripts = {
        "vaultsync.bash": render_bash(children, options),
        "_vaultsync": render_zsh(children, options),
        "vaultsync.ps1": render_powershell(children, options),
    }
    if args.check:
        stale = [name for name, content in scripts.items()
                 if not (output / name).is_file() or (output / name).read_text(encoding="utf-8") != content]
        if stale:
            raise SystemExit(f"CLI completion scripts are stale: {', '.join(stale)}")
        print("CLI completion scripts are current.")
        return
    output.mkdir(parents=True, exist_ok=True)
    for name, content in scripts.items():
        (output / name).write_text(content, encoding="utf-8")
        print(f"Wrote {output / name}")


if __name__ == "__main__":
    main()
