#!/usr/bin/env python3
"""Generate the exhaustive VaultSync CLI command-help reference."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import subprocess
from typing import Callable, Sequence

COMMANDS: tuple[tuple[str, ...], ...] = (
    (),
    ("projects",), ("projects", "add"), ("projects", "list"), ("projects", "show"),
    ("projects", "discover"), ("projects", "set-path"), ("projects", "remove"),
    ("snapshots",), ("snapshots", "create"), ("snapshots", "list"),
    ("snapshots", "show"), ("snapshots", "diff"), ("snapshots", "prune"),
    ("recovery",), ("recovery", "restore"), ("mirror",), ("verify",), ("watch",),
    ("doctor",), ("destinations",), ("self-test",), ("init",),
    ("config",), ("config", "show"), ("config", "path"), ("config", "set-db"),
    ("presets",), ("presets", "list"), ("presets", "show"), ("version",), ("docs",),
    ("add-project",), ("remove-project",), ("list-projects",), ("set-path",),
    ("update-path",), ("snapshot",), ("sync",), ("restore",), ("history",),
    ("diff",), ("prune",),
)
ANSI_ESCAPE = re.compile(r"\x1b\[[0-?]*[ -/]*[@-~]")


def normalize_help(text: str) -> str:
    normalized = ANSI_ESCAPE.sub("", text).replace("VaultSync.CLI.dll", "vaultsync")
    return "\n".join(line.rstrip() for line in normalized.strip().splitlines())


def render_document(run_help: Callable[[Sequence[str]], str]) -> str:
    lines = [
        "# VaultSync CLI generated command reference",
        "",
        "<!-- Generated by scripts/generate_cli_reference.py. Do not edit manually. -->",
        "",
        "This reference is generated from the registered command tree. The practical handbook is",
        "[CLI.md](CLI.md). Run `vaultsync COMMAND --help` against your installed version for",
        "the authoritative options supported by that executable.",
        "",
    ]
    for command in COMMANDS:
        display = "vaultsync" + (" " + " ".join(command) if command else "")
        lines.extend((f"## `{display}`", "", "```text", normalize_help(run_help(command)), "```", ""))
    return "\n".join(lines).rstrip() + "\n"


def generate(assembly: Path) -> str:
    if not assembly.is_file():
        raise FileNotFoundError(f"CLI assembly not found: {assembly}")
    environment = os.environ.copy()
    environment.update({"COLUMNS": "120", "NO_COLOR": "1"})

    def run_help(command: Sequence[str]) -> str:
        completed = subprocess.run(
            ["dotnet", str(assembly), *command, "--help"],
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=environment,
        )
        return completed.stdout

    return render_document(run_help)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--assembly", default="src/VaultSync.CLI/bin/Debug/net10.0/VaultSync.CLI.dll")
    parser.add_argument("--output", default="docs/CLI_COMMAND_REFERENCE.md")
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    assembly = Path(args.assembly).resolve()
    output = Path(args.output).resolve()
    rendered = generate(assembly)
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"CLI command reference is stale: run {Path(__file__).name}")
        print(f"CLI command reference is current: {output}")
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
