# Generated by scripts/generate_cli_completions.py. Do not edit manually.
_vaultsync_children() {
  case "$1" in
    '') printf '%s' 'projects snapshots recovery mirror prune set-path update-path restore history diff self-test init add-project remove-project list-projects snapshot sync verify watch doctor destinations version docs completion config presets' ;;
    'projects') printf '%s' 'add list show discover set-path remove' ;;
    'snapshots') printf '%s' 'create list show diff prune' ;;
    'recovery') printf '%s' 'restore' ;;
    'config') printf '%s' 'show path set-db' ;;
    'presets') printf '%s' 'list show' ;;
    'completion') printf '%s' 'bash zsh powershell' ;;
  esac
}
_vaultsync_options() {
  case "$1" in
    '') printf '%s' '-h --help --version' ;;
    'projects') printf '%s' '-h --help' ;;
    'projects add') printf '%s' '-h --help --preset --db --quiet' ;;
    'projects list') printf '%s' '-h --help --db --json --output --filter --preset --limit' ;;
    'projects show') printf '%s' '-h --help --id --db --output' ;;
    'projects discover') printf '%s' '-h --help --root --json' ;;
    'projects set-path') printf '%s' '-h --help --db --quiet' ;;
    'projects remove') printf '%s' '-h --help --db --yes --quiet' ;;
    'snapshots') printf '%s' '-h --help' ;;
    'snapshots create') printf '%s' '-h --help --full-hash --db --quiet' ;;
    'snapshots list') printf '%s' '-h --help --db --json --output --limit' ;;
    'snapshots show') printf '%s' '-h --help --id --db --output' ;;
    'snapshots diff') printf '%s' '-h --help --db --limit --json --output' ;;
    'snapshots prune') printf '%s' '-h --help --keep-last --before --dry-run --db --quiet --json' ;;
    'recovery') printf '%s' '-h --help' ;;
    'recovery restore') printf '%s' '-h --help --snapshot --dry-run --clean --keep-empty-dirs --db --quiet --json' ;;
    'mirror') printf '%s' '-h --help --dry-run --db --quiet' ;;
    'verify') printf '%s' '-h --help --percent --full --db --quiet --json' ;;
    'watch') printf '%s' '-h --help --db --dest --debounce-ms --sync --verify --dry-run --quiet' ;;
    'doctor') printf '%s' '-h --help --db --check-dest --quiet' ;;
    'destinations') printf '%s' '-h --help --test --json' ;;
    'self-test') printf '%s' '-h --help --db --quiet' ;;
    'init') printf '%s' '-h --help --db --quiet' ;;
    'config') printf '%s' '-h --help' ;;
    'config show') printf '%s' '-h --help' ;;
    'config path') printf '%s' '-h --help' ;;
    'config set-db') printf '%s' '-h --help' ;;
    'presets') printf '%s' '-h --help' ;;
    'presets list') printf '%s' '-h --help' ;;
    'presets show') printf '%s' '-h --help' ;;
    'version') printf '%s' '-h --help --json' ;;
    'docs') printf '%s' '-h --help --full --open --url --task' ;;
    'completion') printf '%s' '-h --help' ;;
    'add-project') printf '%s' '-h --help --preset --db --quiet' ;;
    'remove-project') printf '%s' '-h --help --db --yes --quiet' ;;
    'list-projects') printf '%s' '-h --help --db --json --output --filter --preset --limit' ;;
    'set-path') printf '%s' '-h --help --db --quiet' ;;
    'update-path') printf '%s' '-h --help --db --quiet' ;;
    'snapshot') printf '%s' '-h --help --full-hash --db --quiet' ;;
    'sync') printf '%s' '-h --help --dry-run --db --quiet' ;;
    'restore') printf '%s' '-h --help --snapshot --dry-run --clean --keep-empty-dirs --db --quiet --json' ;;
    'history') printf '%s' '-h --help --db --json --output --limit' ;;
    'diff') printf '%s' '-h --help --db --limit --json --output' ;;
    'prune') printf '%s' '-h --help --keep-last --before --dry-run --db --quiet --json' ;;
  esac
}

_vaultsync_complete() {
  local current="${COMP_WORDS[COMP_CWORD]}" route='' word choices child
  local index
  for ((index = 1; index < COMP_CWORD; index++)); do
    word="${COMP_WORDS[index]}"
    choices="$(_vaultsync_children "$route")"
    case " $choices " in
      *" $word "*) route="${route:+$route }$word" ;;
    esac
  done
  if [[ "$current" == -* ]]; then
    choices="$(_vaultsync_options "$route")"
  else
    choices="$(_vaultsync_children "$route")"
  fi
  COMPREPLY=( $(compgen -W "$choices" -- "$current") )
}
complete -F _vaultsync_complete vaultsync
