# Generated by scripts/generate_cli_completions.py. Do not edit manually.
_vaultsync_children() {
  case "$1" in
    '') printf '%s' 'docs completion prune set-path update-path restore history diff self-test init add-project remove-project list-projects snapshot sync verify watch doctor destinations version config presets' ;;
    'config') printf '%s' 'show path set-db' ;;
    'presets') printf '%s' 'list show' ;;
    'completion') printf '%s' 'bash zsh powershell' ;;
  esac
}
_vaultsync_options() {
  case "$1" in
    '') printf '%s' '-h --help --version' ;;
    'config') printf '%s' '-h --help' ;;
    'config show') printf '%s' '-h --help' ;;
    'config path') printf '%s' '-h --help' ;;
    'config set-db') printf '%s' '-h --help' ;;
    'presets') printf '%s' '-h --help' ;;
    'presets list') printf '%s' '-h --help' ;;
    'presets show') printf '%s' '-h --help' ;;
    'verify') printf '%s' '-h --help --percent --full --db --quiet --json' ;;
    'watch') printf '%s' '-h --help --db --dest --debounce-ms --sync --verify --dry-run --quiet' ;;
    'doctor') printf '%s' '-h --help --db --check-dest --quiet' ;;
    'destinations') printf '%s' '-h --help --test --json' ;;
    'self-test') printf '%s' '-h --help --db --quiet' ;;
    'init') printf '%s' '-h --help --db --quiet' ;;
    'version') printf '%s' '-h --help --json' ;;
    'docs') printf '%s' '-h --help --full --open --url --task' ;;
    'completion') printf '%s' '-h --help' ;;
    'add-project') printf '%s' '-h --help --preset --db --quiet' ;;
    'remove-project') printf '%s' '-h --help --db --yes --quiet' ;;
    'list-projects') printf '%s' '-h --help --db --json' ;;
    'set-path') printf '%s' '-h --help --db --quiet' ;;
    'update-path') printf '%s' '-h --help --db --quiet' ;;
    'snapshot') printf '%s' '-h --help --full-hash --db --quiet' ;;
    'sync') printf '%s' '-h --help --dry-run --db --quiet' ;;
    'restore') printf '%s' '-h --help --snapshot --dry-run --clean --keep-empty-dirs --db --quiet --json' ;;
    'history') printf '%s' '-h --help --db --json --limit' ;;
    'diff') printf '%s' '-h --help --db --limit --json' ;;
    'prune') printf '%s' '-h --help --keep-last --before --dry-run --db --quiet --json' ;;
  esac
}
_vaultsync_values() {
  case "$1" in
    'docs --task') printf '%s' 'setup inspect mirror restore automate migrate' ;;
  esac
}

_vaultsync_complete() {
  local current="${COMP_WORDS[COMP_CWORD]}" route='' word choices
  local index
  for ((index = 1; index < COMP_CWORD; index++)); do
    word="${COMP_WORDS[index]}"
    choices="$(_vaultsync_children "$route")"
    case " $choices " in
      *" $word "*) route="${route:+$route }$word" ;;
    esac
  done
  choices="$(_vaultsync_values "$route ${COMP_WORDS[COMP_CWORD-1]}")"
  if [[ -z "$choices" ]]; then
    if [[ "$current" == -* ]]; then
      choices="$(_vaultsync_options "$route")"
    else
      choices="$(_vaultsync_children "$route")"
    fi
  fi
  COMPREPLY=( $(compgen -W "$choices" -- "$current") )
}
complete -F _vaultsync_complete vaultsync
