# Generated by scripts/generate_cli_completions.py. Do not edit manually.
function Get-VaultSyncChildren([string]$route) {
    switch ($route) {
        '' { return 'projects snapshots backups recovery mirror prune set-path update-path restore history diff self-test init add-project remove-project list-projects snapshot sync verify watch doctor destinations version docs completion config presets' }
        'projects' { return 'add list show discover set-path remove' }
        'snapshots' { return 'create list show diff prune' }
        'backups' { return 'create list show verify' }
        'recovery' { return 'restore' }
        'config' { return 'show path set-db' }
        'presets' { return 'list show' }
        'completion' { return 'bash zsh powershell' }
    }
    return ''
}
function Get-VaultSyncOptions([string]$route) {
    switch ($route) {
        '' { return '-h --help --version' }
        'projects' { return '-h --help' }
        'projects add' { return '-h --help --preset --db --quiet' }
        'projects list' { return '-h --help --db --json --output --filter --preset --limit' }
        'projects show' { return '-h --help --id --db --output' }
        'projects discover' { return '-h --help --root --json' }
        'projects set-path' { return '-h --help --db --quiet' }
        'projects remove' { return '-h --help --db --yes --quiet' }
        'snapshots' { return '-h --help' }
        'snapshots create' { return '-h --help --full-hash --db --quiet' }
        'snapshots list' { return '-h --help --db --json --output --limit' }
        'snapshots show' { return '-h --help --id --db --output' }
        'snapshots diff' { return '-h --help --db --limit --json --output' }
        'snapshots prune' { return '-h --help --keep-last --before --dry-run --db --quiet --json' }
        'backups' { return '-h --help' }
        'backups create' { return '-h --help --destination --db --dry-run --quiet --output' }
        'backups list' { return '-h --help --db --limit --output' }
        'backups show' { return '-h --help --id --db --output' }
        'backups verify' { return '-h --help --id --db --limit --output' }
        'recovery' { return '-h --help' }
        'recovery restore' { return '-h --help --snapshot --backup-id --include --dry-run --clean --keep-empty-dirs --db --quiet --json --output' }
        'mirror' { return '-h --help --dry-run --db --quiet' }
        'verify' { return '-h --help --percent --full --db --quiet --json' }
        'watch' { return '-h --help --db --dest --debounce-ms --sync --verify --dry-run --quiet' }
        'doctor' { return '-h --help --db --check-dest --quiet' }
        'destinations' { return '-h --help --test --json' }
        'self-test' { return '-h --help --db --quiet' }
        'init' { return '-h --help --db --quiet' }
        'config' { return '-h --help' }
        'config show' { return '-h --help' }
        'config path' { return '-h --help' }
        'config set-db' { return '-h --help' }
        'presets' { return '-h --help' }
        'presets list' { return '-h --help' }
        'presets show' { return '-h --help' }
        'version' { return '-h --help --json' }
        'docs' { return '-h --help --full --open --url --task' }
        'completion' { return '-h --help' }
        'add-project' { return '-h --help --preset --db --quiet' }
        'remove-project' { return '-h --help --db --yes --quiet' }
        'list-projects' { return '-h --help --db --json --output --filter --preset --limit' }
        'set-path' { return '-h --help --db --quiet' }
        'update-path' { return '-h --help --db --quiet' }
        'snapshot' { return '-h --help --full-hash --db --quiet' }
        'sync' { return '-h --help --dry-run --db --quiet' }
        'restore' { return '-h --help --snapshot --backup-id --include --dry-run --clean --keep-empty-dirs --db --quiet --json --output' }
        'history' { return '-h --help --db --json --output --limit' }
        'diff' { return '-h --help --db --limit --json --output' }
        'prune' { return '-h --help --keep-last --before --dry-run --db --quiet --json' }
    }
    return ''
}
function Get-VaultSyncValues([string]$route) {
    switch ($route) {
        'projects list --output' { return 'text json' }
        'projects show --output' { return 'text json' }
        'snapshots list --output' { return 'text json' }
        'snapshots show --output' { return 'text json' }
        'snapshots diff --output' { return 'text json' }
        'backups create --output' { return 'text json' }
        'backups list --output' { return 'text json' }
        'backups show --output' { return 'text json' }
        'backups verify --output' { return 'text json' }
        'recovery restore --output' { return 'text json' }
        'list-projects --output' { return 'text json' }
        'restore --output' { return 'text json' }
        'history --output' { return 'text json' }
        'diff --output' { return 'text json' }
        'docs --task' { return 'setup inspect mirror restore automate migrate' }
    }
    return ''
}

Register-ArgumentCompleter -Native -CommandName vaultsync -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $route = ''
    $previous = ''
    foreach ($element in @($commandAst.CommandElements | Select-Object -Skip 1)) {
        if ($element.Extent.EndOffset -ge $cursorPosition) { break }
        $word = $element.Extent.Text.Trim('"', "'")
        $previous = $word
        $children = @((Get-VaultSyncChildren $route) -split ' ')
        if ($children -contains $word) {
            if ($route) { $route = "$route $word" } else { $route = $word }
        }
    }
    $choices = Get-VaultSyncValues "$route $previous"
    if (-not $choices) {
        if ($wordToComplete.StartsWith('-')) {
            $choices = Get-VaultSyncOptions $route
        } else {
            $choices = Get-VaultSyncChildren $route
        }
    }
    foreach ($choice in @($choices -split ' ')) {
        if ($choice -and $choice.StartsWith($wordToComplete, [StringComparison]::OrdinalIgnoreCase)) {
            [System.Management.Automation.CompletionResult]::new($choice, $choice, 'ParameterValue', $choice)
        }
    }
}
